"""Cross-skill contract tests for pax-* family.

Every contract is a function ``(family_root: Path) -> list[str]`` returning
violation messages. Empty list = pass.

All contracts resolve the family's single-source-of-truth files from
``family_root`` (never from the tool's install location), so a family
generated by ``pax-forge init`` is checked against its own schema/versions.
"""
from __future__ import annotations

import json as _json
import re as _re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Iterable

import jsonschema

from pax.forge import loader
from pax.forge.validator import _split_frontmatter

ContractFn = Callable[[Path], list[str]]

_CONTRACTS: dict[str, ContractFn] = {}


def register_contract(name: str):
    def deco(fn: ContractFn) -> ContractFn:
        _CONTRACTS[name] = fn
        return fn
    return deco


def list_contracts() -> list[str]:
    return sorted(_CONTRACTS.keys())


@dataclass
class ContractReport:
    ok: bool = True
    failures: list[str] = field(default_factory=list)
    passes: list[str] = field(default_factory=list)

    def add_pass(self, name: str) -> None:
        self.passes.append(name)

    def add_fail(self, name: str, messages: list[str]) -> None:
        self.ok = False
        for m in messages:
            self.failures.append(f"[{name}] {m}")


def run_all_contracts(family_root: Path) -> ContractReport:
    report = ContractReport()
    for name, fn in _CONTRACTS.items():
        try:
            violations = fn(family_root)
        except Exception as exc:
            report.add_fail(name, [f"contract raised: {exc!r}"])
            continue
        if violations:
            report.add_fail(name, violations)
        else:
            report.add_pass(name)
    return report


def _iter_skill_dirs(family_root: Path) -> Iterable[Path]:
    skills_dir = family_root / "skills"
    if not skills_dir.exists():
        return
    for child in skills_dir.iterdir():
        if child.is_dir() and (child / "SKILL.md").exists():
            yield child


def _root(family_root: Path) -> Path | None:
    """A partial fixture directory is not a family root: fall back to the
    tool's own family so contracts can still be exercised against it."""
    return loader.resolve_family_root(family_root)


def _skill_docs(family_root: Path) -> Iterable[tuple[str, dict | None, str]]:
    """Yield (skill_name, frontmatter, body) for every skill."""
    for skill_dir in _iter_skill_dirs(family_root):
        text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
        fm, body = _split_frontmatter(text)
        name = (fm or {}).get("name") or skill_dir.name
        yield name, fm, body


def _mentioned_skills(body: str, self_name: str) -> set[str]:
    return set(_re.findall(r"pax-[a-z][a-z0-9-]*", body)) - {self_name}


# ----- 契约①：frontmatter 完整性 -----

@register_contract("frontmatter-completeness")
def check_frontmatter_completeness(family_root: Path) -> list[str]:
    violations: list[str] = []
    family = loader.load_family_schema(family_root=_root(family_root))
    required = family["contracts"]["required_frontmatter"]
    naming_re = _re.compile(family["contracts"]["naming"])
    for skill_dir in _iter_skill_dirs(family_root):
        text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
        fm, _ = _split_frontmatter(text)
        if fm is None:
            violations.append(
                f"{skill_dir.name}: invalid or missing frontmatter"
            )
            continue
        for key in required:
            if key not in fm:
                violations.append(
                    f"{skill_dir.name}: frontmatter missing '{key}'"
                )
        if not naming_re.match(fm.get("name", "")):
            violations.append(
                f"{skill_dir.name}: name violates naming contract"
            )
    return violations


# ----- 契约②：snapshot schema 合法性 -----

@register_contract("snapshot-schema-validity")
def check_snapshot_schema_validity(family_root: Path) -> list[str]:
    violations: list[str] = []
    schema_path = loader.family_paths(_root(family_root))["snapshot_schema"]
    if not schema_path.exists():
        return [f"missing {schema_path}"]
    with schema_path.open("r", encoding="utf-8") as f:
        schema = _json.load(f)
    try:
        jsonschema.Draft202012Validator.check_schema(schema)
    except jsonschema.SchemaError as exc:
        violations.append(f"snapshot schema invalid: {exc.message}")
    return violations


# ----- 契约③：skill 声明的快照字段必须存在于 snapshot schema -----

# 排除文件名/后缀形式的引用（schemas/snapshot.schema.json、pax-snapshot.yaml）
_SNAPSHOT_REF_RE = _re.compile(
    r"\bsnapshot\.([a-z_][a-z0-9_]*)(?:\.([a-z_][a-z0-9_]*))?"
)
_SNAPSHOT_REF_SKIP = {"schema", "yaml", "json"}


@register_contract("snapshot-field-conformance")
def check_snapshot_field_conformance(family_root: Path) -> list[str]:
    """每个 skill 提到/写入的 ``snapshot.<section>[.<field>]`` 必须能在
    schemas/snapshot.schema.json 中解析到。这是防止「skill 偷偷写了 schema
    没定义的字段」的机械约束——此前 8 处断裂正是因为缺了这条检查。
    """
    snapshot = loader.load_snapshot_schema(family_root=_root(family_root))
    props: dict = snapshot.get("properties", {})
    violations: set[str] = set()
    for name, _fm, body in _skill_docs(family_root):
        for match in _SNAPSHOT_REF_RE.finditer(body):
            section, sub = match.group(1), match.group(2)
            if section in _SNAPSHOT_REF_SKIP:
                continue
            if section not in props:
                violations.add(
                    f"{name}: 引用了 snapshot.{section}，"
                    f"但 snapshot.schema.json 无此顶层字段"
                )
                continue
            if sub is None:
                continue
            sub_props = props[section].get("properties")
            # 只声明了 {"type": "object"} 的段（如 diagnosis）不做二级校验
            if not sub_props:
                continue
            if sub not in sub_props:
                violations.add(
                    f"{name}: 引用了 snapshot.{section}.{sub}，"
                    f"但 schema 中 {section} 未声明该字段"
                )
    return sorted(violations)


# ----- 契约④：层间调用合法性 -----

def _allowed_calls(family_root: Path | None = None) -> set[tuple[str, str]]:
    """允许的层间调用方向，权威源是 versions.json 的 compatibility_matrix。"""
    versions = loader.load_versions(family_root=_root(family_root))
    matrix = versions.get("compatibility_matrix", {})
    return {
        (src, tgt)
        for src, targets in matrix.items()
        if not src.startswith("_") and isinstance(targets, list)
        for tgt in targets
    }


@register_contract("layer-call-legality")
def check_layer_call_legality(family_root: Path) -> list[str]:
    allowed = _allowed_calls(family_root)
    violations: list[str] = []
    skill_layers: dict[str, str] = {}
    for name, fm, _body in _skill_docs(family_root):
        if fm and "layer" in fm:
            skill_layers[name] = fm["layer"]
    for name, fm, body in _skill_docs(family_root):
        if fm is None:
            continue
        self_layer = fm.get("layer")
        for target_name in _mentioned_skills(body, name):
            target_layer = skill_layers.get(target_name)
            if target_layer is None:
                continue
            if (self_layer, target_layer) not in allowed:
                violations.append(
                    f"{name} ({self_layer}) references "
                    f"{target_name} ({target_layer}): forbidden direction"
                )
    return violations


# ----- 契约⑤：schema.layers 与实际成员一致 -----

@register_contract("layer-membership")
def check_layer_membership(family_root: Path) -> list[str]:
    """schemas/pax-family.schema.yaml 的 layers 枚举必须与 registry.json 一致。

    schema.layers 此前是没人读的死数据，L1 缺 5 个、L4 缺 1 个也无人发现。
    """
    family = loader.load_family_schema(family_root=_root(family_root))
    registry = loader.load_registry(family_root=_root(family_root))
    layers: dict = family.get("layers", {})
    non_runtime = set(family.get("non_runtime_layers", []))

    actual_suffixes = {
        d.name[len("pax-"):] for d in _iter_skill_dirs(family_root)
        if d.name.startswith("pax-")
    }
    declared: dict[str, str] = {}
    for layer, members in layers.items():
        for member in members:
            if member.endswith("*"):
                prefix = member[:-1]
                for suffix in actual_suffixes:
                    if suffix.startswith(prefix):
                        declared[f"pax-{suffix}"] = layer
            else:
                declared[f"pax-{member}"] = layer

    registered = {e["name"]: e.get("layer") for e in registry.get("skills", [])}
    violations: list[str] = []

    for name, layer in registered.items():
        want = declared.get(name)
        if want is None:
            violations.append(
                f"{name}: 注册为 {layer}，但未出现在 "
                f"schemas/pax-family.schema.yaml 的 layers 中"
            )
        elif want != layer:
            violations.append(
                f"{name}: registry layer={layer} != schema.layers={want}"
            )

    for layer, members in layers.items():
        if layer in non_runtime:
            continue
        for member in members:
            if member.endswith("*"):
                continue
            name = f"pax-{member}"
            if name not in registered:
                violations.append(
                    f"{name}: 在 schema.layers.{layer} 声明，但未注册到 registry.json"
                )
    return violations


# ----- 契约⑥：compatibility_matrix 自洽 -----

@register_contract("compatibility-matrix-consistency")
def check_compatibility_matrix_consistency(family_root: Path) -> list[str]:
    versions = loader.load_versions(family_root=_root(family_root))
    family = loader.load_family_schema(family_root=_root(family_root))
    registry = loader.load_registry(family_root=_root(family_root))
    violations: list[str] = []

    matrix = versions.get("compatibility_matrix")
    if not isinstance(matrix, dict) or not matrix:
        return ["versions.json: compatibility_matrix 缺失或为空对象"]

    layers = set(family.get("layers", {}).keys())
    registered = {e["name"] for e in registry.get("skills", [])}

    for src, targets in matrix.items():
        if src.startswith("_"):
            continue
        if src not in layers:
            violations.append(
                f"compatibility_matrix: 源层 {src} 不是 schema.layers 中已知的层"
            )
        if not isinstance(targets, list):
            violations.append(
                f"compatibility_matrix[{src}]: 必须是层名数组"
            )
            continue
        for tgt in targets:
            if tgt not in layers:
                violations.append(
                    f"compatibility_matrix[{src}]: 目标层 {tgt} 不是已知的层"
                )
            if tgt in family.get("non_runtime_layers", []):
                violations.append(
                    f"compatibility_matrix[{src}]: 不允许调用非运行时层 {tgt}"
                )

    flow = versions.get("main_flow", {}).get("path", [])
    for skill in flow:
        if skill not in registered:
            violations.append(
                f"main_flow: {skill} 不是 registry.json 中的已注册 skill"
            )
    # 主干链上的每一步都必须是可被前一步调用的方向
    for prev, cur in zip(flow, flow[1:]):
        prev_layer = next((e.get("layer") for e in registry.get("skills", [])
                           if e["name"] == prev), None)
        cur_layer = next((e.get("layer") for e in registry.get("skills", [])
                          if e["name"] == cur), None)
        if prev_layer and cur_layer and (prev_layer, cur_layer) not in _allowed_calls(family_root):
            violations.append(
                f"main_flow: {prev} ({prev_layer}) → {cur} ({cur_layer}) "
                f"不在 compatibility_matrix 允许的方向内"
            )
    return violations


# ----- 契约⑦：版本一致性 -----

@register_contract("version-consistency")
def check_version_consistency(family_root: Path) -> list[str]:
    versions_path = loader.family_paths(_root(family_root))["versions"]
    if not versions_path.exists():
        return ["missing pax-ops/versions.json"]
    with versions_path.open("r", encoding="utf-8") as f:
        versions = _json.load(f)
    known = versions.get("skills", {})
    violations: list[str] = []
    for name, fm, _body in _skill_docs(family_root):
        if fm is None:
            continue
        if name not in known:
            violations.append(
                f"{name}: not listed in pax-ops/versions.json"
            )
            continue
        if known[name].get("version") != fm.get("version"):
            violations.append(
                f"{name}: SKILL.md version {fm.get('version')!r} != "
                f"versions.json {known[name].get('version')!r}"
            )
    return violations


# ----- 契约⑧：无循环依赖 -----

def _extract_call_graph(family_root: Path) -> dict[str, set[str]]:
    graph: dict[str, set[str]] = {}
    for name, fm, body in _skill_docs(family_root):
        if fm is None:
            continue
        graph[name] = _mentioned_skills(body, name)
    return graph


def _find_cycles(graph: dict[str, set[str]]) -> list[list[str]]:
    cycles: list[list[str]] = []
    seen_global: set[tuple[str, ...]] = set()
    visited: set[str] = set()
    path: list[str] = []

    def dfs(node: str):
        if node in path:
            cyc = tuple(path[path.index(node):])
            if cyc not in seen_global:
                seen_global.add(cyc)
                cycles.append(list(cyc) + [node])
            return
        if node in visited:
            return
        visited.add(node)
        path.append(node)
        for nxt in sorted(graph.get(node, ())):
            if nxt in graph:
                dfs(nxt)
        path.pop()

    for node in sorted(graph):
        visited.clear()
        path.clear()
        dfs(node)
    return cycles


@register_contract("no-cycles")
def check_no_cycles(family_root: Path) -> list[str]:
    graph = _extract_call_graph(family_root)
    cycles = _find_cycles(graph)
    return [f"cycle detected: {' -> '.join(c)}" for c in cycles]


# ----- 契约⑨：跳过审计 -----

SKIP_AUDIT_KEYWORDS = ("skip_reason", "跳过留痕", "跳过理由")


@register_contract("skip-audit")
def check_skip_audit(family_root: Path) -> list[str]:
    violations: list[str] = []
    for name, fm, body in _skill_docs(family_root):
        if fm is None:
            continue
        if not fm.get("optional", False):
            continue
        if not any(k in body for k in SKIP_AUDIT_KEYWORDS):
            violations.append(
                f"{name}: optional skill must document "
                f"skip_reason (跳过留痕契约)"
            )
    return violations


# ----- 契约⑩：门禁行为 -----

GATE_KEYWORDS = ("前置门禁", "前置条件", "未通过", "不满足", "禁止", "降级")


@register_contract("gate-behavior")
def check_gate_behavior(family_root: Path) -> list[str]:
    violations: list[str] = []
    for name, fm, body in _skill_docs(family_root):
        if fm is None:
            continue
        marker = "## Execution Contract"
        if marker not in body:
            violations.append(
                f"{name}: missing Execution Contract section"
            )
            continue
        section = body.split(marker, 1)[1]
        if "\n## " in section:
            section = section.split("\n## ", 1)[0]
        if not any(k in section for k in GATE_KEYWORDS):
            violations.append(
                f"{name}: Execution Contract lacks precondition/gate keyword"
            )
    return violations


# ----- 契约⑩b：门禁失败必须拒绝启动（不得以降级继续偷换） -----
# 背景：pax-orchestrate 是 L0 强制编排入口，其 Execution Contract 要求「未通过门禁：
# 拒绝启动，返回用户错误」。但旧实现里契约⑩只是「段落里存在门禁关键词」就通过，
# 不校验「门禁失败处置」到底是拒绝启动还是降级继续。AGENTS.md 模板又把
# 「环境降级 MUST 随交付提示」写成泛化规则，Agent 于是在 schema/versions 缺失时选择
# 「降级继续」而非「拒绝启动」——两处契约互相矛盾。本契约做语义级兜底：
#   - 凡声明了门禁/前置条件的 skill，其未通过处置若只写「降级/继续执行」而不含
#     「拒绝/blocked/禁止启动」，判违规；
#   - L0 强制入口（orchestrate）必须显式含「拒绝启动 / 返回 blocked / 返回错误 /
#     禁止/不得开始/不可继续」之一，且不得把门禁失败包装为「可降级继续」。

GATE_REFUSE_TOKENS = (
    "拒绝启动", "拒绝", "返回 blocked", "返回错误", "返回用户错误",
    "禁止", "不得开始", "不可继续", "不得继续", "must not", "MUST NOT",
)
GATE_DEGRADE_TOKENS = (
    "降级后继续", "降级继续", "继续执行", "不阻塞", "仍执行", "仍继续",
    "放行并继续", "静默降级", "继续流程",
)


def _exec_contract_section(body: str) -> str | None:
    marker = "## Execution Contract"
    if marker not in body:
        return None
    section = body.split(marker, 1)[1]
    if "\n## " in section:
        section = section.split("\n## ", 1)[0]
    return section


@register_contract("gate-refusal")
def check_gate_refusal(family_root: Path) -> list[str]:
    violations: list[str] = []
    for name, fm, body in _skill_docs(family_root):
        if fm is None:
            continue
        section = _exec_contract_section(body)
        if section is None:
            continue  # missing Execution Contract 由 gate-behavior 覆盖
        is_l0_forced = (
            fm.get("layer") == "L0"
            and str(fm.get("optional", "true")).strip().lower() != "true"
        )
        # 只有声明了门禁/前置条件的段落才做语义校验
        has_gate_decl = any(k in section for k in GATE_KEYWORDS)
        if not has_gate_decl:
            continue
        has_refuse = any(k in section for k in GATE_REFUSE_TOKENS)
        has_degrade = any(k in section for k in GATE_DEGRADE_TOKENS)
        # 规则1：声明门禁却只有「降级继续」、无任何拒绝语义 → 违规（可能被 Agent 当成可降级继续）
        if has_degrade and not has_refuse:
            violations.append(
                f"{name}: 门禁/前置条件段落声明了降级继续但不含拒绝语义"
                f"（拒绝启动/blocked/返回错误/禁止），会被 Agent 当成可降级继续而绕过门禁"
            )
        # 规则2：L0 强制入口必须显式拒绝启动，且不得用降级偷换
        if is_l0_forced and not has_refuse:
            violations.append(
                f"{name}: L0 强制入口的门禁段落必须显式声明拒绝启动/返回 blocked/返回错误，"
                f"不得把门禁失败包装为降级继续"
            )
        if is_l0_forced and has_degrade and not has_refuse:
            violations.append(
                f"{name}: L0 强制入口不得以降级继续的方式处置门禁失败，必须拒绝启动"
            )
    return violations


# ----- 契约⑪：schema 声明的检查项与实现一致 -----

@register_contract("declared-checks-coverage")
def check_declared_checks_coverage(family_root: Path) -> list[str]:
    """schemas/pax-family.schema.yaml 的 contracts.declared_checks 必须与
    contracts.py 实际注册的契约名集合一致（双向）。
    """
    family = loader.load_family_schema(family_root=_root(family_root))
    declared = set(family.get("contracts", {}).get("declared_checks", []))
    implemented = {n for n in _CONTRACTS if n != "declared-checks-coverage"}
    violations: list[str] = []
    for name in sorted(declared - implemented):
        violations.append(
            f"schema 声明了检查 {name!r}，但 contracts.py 未实现"
        )
    for name in sorted(implemented - declared):
        violations.append(
            f"contracts.py 实现了检查 {name!r}，但 schema 未声明"
        )
    return violations
